---
- name: create vaibles
  hosts: all
  become: yes
  tasks: 
    - name: create directory variable
      ansible.builtin.file:
        path: "{{ DIRECTORY }}"
        state: directory


    - name: create file
      ansible.builtin.file:
        path: "{{ FILE }}"
        state: touch

    - name: create content
      ansible.builtin.copy:
        content: "{{ CONTENT }}"
        dest: "{{ DIRECTORY }}/{{ FILE }}"
      
