---
- name: define variables
  hosts: all
  become: yes
  tasks:
    - name: create directory
      ansible.builtin.file:
        path: "{{ DIRECTORY }}"
        state: directory

    - name: create file
      ansible.builtin.file:
        path: "{{ FILE }}"
        state: touch

    - name: create content
      anible.builtin.copy:
        content: "{{ CONTENT }}"
        dest: "{{ DIRECTORY }}/{{ FILE }}"

